<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter field for certifications_filte_73e64a</name>
   <tag></tag>
   <elementGuidId>053e8afb-5c05-4ad4-b3f1-9b16869450dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter-certified-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#filter-certified-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>888ba8e0-5ebd-481a-af56-4b646915bf90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter-certified-input</value>
      <webElementGuid>2fa4c3ad-4f82-4761-8aad-581c23e704df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>TopNavBar.filter(event, 'nav_certified')</value>
      <webElementGuid>93c62f50-9057-4ac5-bb03-5356afe43d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f7ef263-7f87-4da3-ba79-263861921d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-input</value>
      <webElementGuid>7a440f1e-608d-4801-b5b1-15edc61beab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Filter...</value>
      <webElementGuid>e41655c2-c9d7-4a05-b8c6-897bcb053f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Certificate filter bar</value>
      <webElementGuid>aab55cb7-e3f6-4fa4-9d5d-a80c4d3c5e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-certified-input&quot;)</value>
      <webElementGuid>f70a09eb-f067-4774-b9cd-6c75f61acfd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter-certified-input']</value>
      <webElementGuid>b2f68c7e-0752-4b5c-970f-378140903171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='certified_list']/div/div[2]/div/input</value>
      <webElementGuid>2919a455-a382-46a8-a62b-d26a2a655de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[3]/div/div/div/div[2]/div/input</value>
      <webElementGuid>e69cbbca-5c1a-4a62-8e50-935695353a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'filter-certified-input' and @type = 'text' and @placeholder = 'Filter...']</value>
      <webElementGuid>c2560641-93bd-4476-8804-a0cf27ec0fbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
