<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tutorials filter input_filter-tutoria_e71851</name>
   <tag></tag>
   <elementGuidId>c2e42178-57d5-4b5a-b62e-a15ef7845ebc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#filter-tutorials-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f718daf-2153-40ed-ac6b-9ff58c865239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter-tutorials-input</value>
      <webElementGuid>bd93d3f8-1a8a-4af8-80f8-582f92c2fe80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>TopNavBar.filter(event, 'nav_tutorials')</value>
      <webElementGuid>432683a9-baa1-4669-964e-458d18f9ed7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a4a1c757-b471-4455-aa66-4c97c0f4515c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-input</value>
      <webElementGuid>e8fda73c-d12b-4658-91a1-1db7071661d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Filter...</value>
      <webElementGuid>289da934-4182-40b7-8ecc-89d0e25dea28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Tutorials filter input</value>
      <webElementGuid>bb9edaf3-c437-4aea-814a-0edb81cda3a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-tutorials-input&quot;)</value>
      <webElementGuid>b538e84c-ba4a-436a-90cc-e4ca313297be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter-tutorials-input']</value>
      <webElementGuid>7a98d264-6373-498c-b524-02e5a2aa6a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tutorials_list']/div/div[2]/div/input</value>
      <webElementGuid>6ea7f00a-8bd6-408f-a884-44dcd70f6dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>8520a964-c71f-4d00-b596-7bbf65c6b0eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'filter-tutorials-input' and @type = 'text' and @placeholder = 'Filter...']</value>
      <webElementGuid>5673961c-e369-4134-93b2-ee605bd54975</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
