<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Python Ruby JavaScript Java C</name>
   <tag></tag>
   <elementGuidId>2a27e751-e1f5-48c8-846b-a4e534251bed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_choose_language']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_choose_language</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6cee74ba-4db2-4f81-89f0-629adf3eb79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>choose_language</value>
      <webElementGuid>6d6711b7-9249-4f8b-87b9-dc533d088100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>eaf4b3c4-dd90-4da5-998c-92ac6bb6ea15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_choose_language</value>
      <webElementGuid>f6312085-4aa3-44bf-8f23-b28703ef4422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Python Ruby JavaScript Java C#

</value>
      <webElementGuid>7e72cd04-2140-4ee9-b27c-79aa8c682dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_choose_language&quot;)</value>
      <webElementGuid>6b6461a2-5994-4ccc-acda-3705b74cf5b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_choose_language']</value>
      <webElementGuid>5d7287b9-bc4d-47ee-8dcd-b6603480fc5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_id_choose_language']/select</value>
      <webElementGuid>b9f13b64-a732-489c-962a-dc3a90912cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>8b69c2d2-8b28-4587-a93c-28d597c0ad6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Field name is ', '&quot;', 'Choose language', '&quot;', '')])[1]/preceding::select[1]</value>
      <webElementGuid>6cf83c55-3e64-46be-8a61-15544ba209e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>71c8d5ea-c787-4338-b114-24cf62550f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'choose_language' and @id = 'id_choose_language' and (text() = '  Python Ruby JavaScript Java C#

' or . = '  Python Ruby JavaScript Java C#

')]</value>
      <webElementGuid>6813aa3b-f3f9-4527-8068-4a60cc1d3081</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
