<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__iframeResult</name>
   <tag></tag>
   <elementGuidId>9c7fd88c-de6a-4d52-9383-0c16ac7812e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframeResult']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframeResult</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4125b094-4a3f-42e4-aafe-4ace4ee1fb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cd73f6ad-0711-4a66-925e-4451a93ed5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframeResult</value>
      <webElementGuid>0b4f53b8-937d-47ae-bc16-5bdb6cfa99a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iframeResult</value>
      <webElementGuid>59402b3c-ac4a-4a12-beea-0ba7791c7eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7e49d556-1e19-43b4-a13d-6299a5912d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframeResult&quot;)</value>
      <webElementGuid>7196f66b-9f79-46bf-9ecf-ad69e1f45736</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframeResult']</value>
      <webElementGuid>63abe73c-440e-4775-8d0c-ce1ad8e4e058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iframewrapper']/iframe</value>
      <webElementGuid>418f32dc-3303-4ce1-88b2-f69b1be5b054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/iframe</value>
      <webElementGuid>bd64c698-ef60-4159-ac3f-05d9ce6f583a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframeResult' and @name = 'iframeResult']</value>
      <webElementGuid>6b2cc17f-e89b-48a7-a6a4-58a471b58cde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
